server:
  port: 8090
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
      - id: epsychiatrie
        uri: lb://gestiondesrendezvous-microservice
        predicates:
        - Path=/gestiondesrendezvous/**
      - id: gestiondespsychiatresetpatients
        uri: lb://gestiondespsychiatresetpatients-microservice
        predicates:
        - Path=/gestiondespsychiatresetpatients/**
      - id: gestiondesvisites
        uri: lb://gestiondesvisites-microservice
        predicates:
        - Path=/gestiondesvisites/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8091/eureka/

